### ISSUE TITLE
How to change arrow?

### ISSUE THREAD

**Issue by dqii** [springload/react-accessible-accordion#268]
I really like this library! I was wondering how you would change the arrow icons on the left to be something more custom? For context, I'd like to have a + icon on the right instead.

**Comment by holloway** [comment]
Yes, that could be changed by changing the CSS you're using.

If you've added the `fancy-example.css` example then you could change the CSS Rule `.accordion__button:before`.

It could be something like this (untested, you'll need to change other CSS Rules to make this work)

```css
.accordion__button:before {
    display: inline-block;
    content: '+'; /* note the "+" here */
    height: 10px;
    width: 10px;
    margin-right: 12px;
    transform: rotate(-45deg);
}
```
